apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: elasticsearch
  labels:
    component: monitoring
    app: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    component: monitoring
    app: elasticsearch
