apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: kafka
  labels:
    component: messaging
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    component: messaging
    app: kafka
