apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: kafka
  name: kafka
  labels:
    component: messaging
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: messaging
      app: kafka
  serviceName: kafka
  template:
    metadata:
      name: kafka
      labels:
        component: messaging
        app: kafka
    spec:
      serviceAccountName: kafka
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.3
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "5"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka.kafka.svc.cluster.local:9092,OUTSIDE://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
          ports:
            - containerPort: 9092
