apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: monitoring
  name: filebeat
  labels:
    component: monitoring
    app: filebeat
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: filebeat
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
