apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: filebeat
  labels:
    component: monitoring
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${KUBERNETES_NODE_NAME}
          labels.dedot: true
          templates:
            - condition:
                equals:
                  kubernetes.labels:
                    component: "application"
              config:
                - type: container
                  format: docker
                  paths:
                    - "/var/lib/docker/containers/${data.kubernetes.container.id}/*.log"
                  processors:
                    - decode_json_fields:
                        fields: ["message"]
                        target: ""
                        overwrite_keys: true
                    - add_kubernetes_metadata:
                    - add_cloud_metadata:

    output.logstash:
      hosts: "${LOGSTASH_HOSTNAME}"

    logging.metrics.enabled: false
