apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: monitoring
  name: filebeat
  labels:
    component: monitoring
    app: filebeat
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: filebeat
roleRef:
  kind: Role
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: monitoring
  name: filebeat-kubeadm-config
  labels:
    component: monitoring
    app: filebeat
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: filebeat
roleRef:
  kind: Role
  name: filebeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
