apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: logstash
  labels:
    component: monitoring
    app: logstash
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
  selector:
    component: monitoring
    app: logstash
